// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHId9b5Ex9CRHEtQydS3FEGnbxFozZNA',
    appId: '1:489071176145:android:f9d9fbb4f93946387258f0',
    messagingSenderId: '489071176145',
    projectId: 'conversebot-sadd',
    storageBucket: 'conversebot-sadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxp_4cD1zmZ7YFXd2WtMf35MQppvkE5M',
    appId: '1:489071176145:ios:6e81ff4d66d99ef27258f0',
    messagingSenderId: '489071176145',
    projectId: 'conversebot-sadd',
    storageBucket: 'conversebot-sadd.appspot.com',
    iosClientId: '489071176145-d96sb8reech01b8og3ld7kqkvahd7eoj.apps.googleusercontent.com',
    iosBundleId: 'se.dannyl.flutterbotv2',
  );
}
