// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY9wR2r8On3IFCEgkmxOUdwHvXBYocy2U',
    appId: '1:791194895215:android:90fc14d8f46c0f68511e9a',
    messagingSenderId: '791194895215',
    projectId: 'conversationalform-43d0c',
    storageBucket: 'conversationalform-43d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTfnbqeGmDmrOqhEFjicqmt8ztSXaHeE',
    appId: '1:791194895215:ios:59b5320e09c07ecc511e9a',
    messagingSenderId: '791194895215',
    projectId: 'conversationalform-43d0c',
    storageBucket: 'conversationalform-43d0c.appspot.com',
    iosClientId: '791194895215-dr442pharisqdj6o8oseevckr3g8cfjs.apps.googleusercontent.com',
    iosBundleId: 'se.dannyl.flutterbotv2',
  );
}
